import { Survey } from '../interfaces/survey-interface';
import { getIsoDateFromGermanDate } from '../shared/utils/custom-functions';

/**
 * @description Represents a survey model that implements the Survey interface.
 * This class provides a constructor to initialize survey properties and a method to get a clean JSON representation for adding a new survey.
 * @implements {Survey}
 */
export class SurveyModel implements Survey {
    id: number;
    title: string;
    description: string | null;
    expires_at: string | null;
    category_id: number;
    is_published: boolean;
    created_at: string;

    /**
     * Creates an instance of SurveyModel.
     * Initializes the survey properties.
     * If the expires_at property is provided, it converts it to ISO format using the getIsoDateFromGermanDate function.
     *
     * @param surveyData - Partial data for the survey.
     */
    constructor(surveyData: Partial<Survey> = {}) {
        this.id = surveyData.id ?? 0;
        this.title = surveyData.title ?? '';
        this.description = surveyData.description ?? null;
        this.expires_at = surveyData.expires_at ?? null;
        this.category_id = surveyData.category_id ?? 0;
        this.is_published = surveyData.is_published ?? false;
        this.created_at = surveyData.created_at ?? '';

        if(this.expires_at) {
            this.expires_at = getIsoDateFromGermanDate(this.expires_at);
        }

    }

    /**
     * Returns a clean JSON representation of the survey model for adding a new survey.
     * This method excludes the id and created_at properties, as they are typically generated by the backend.
     * @returns 
     */
    getCleanAddSurveyJson(): {} {
        return {
            title: this.title,
            description: this.description,
            expires_at: this.expires_at,
            category_id: this.category_id,
            is_published: this.is_published
        };
    }

}